### ISSUE TITLE
Sermon Speaker - Series Page - Update Request

### ISSUE THREAD

**Issue by Cdelorm** [delorm-designs/csl-joomla-bs2-template#1]
Robert:

You rock! 

Can you please do that magic you do and remove the cog and email icon from the series page?

Like you did for the speaker page?

http://columbiacsl.org/colcslj3/podcast-archive/serie/3-acceptember

Thank you!

Caprice

**Comment by DoctorWhoCares** [comment]
This issue is now fixed.

Added serie folder to the html overrides and removed lines 31 to 51 from the table.php
